version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: .
      target: backend
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - hatch

  frontend:
    container_name: frontend
    build:
      context: .
      target: frontend
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
    networks:
      - hatch

networks:
  hatch:
    driver: bridge