version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    # image: backend:latest
    ports:
      - 3000:3000
    # volumes:
    #   - .:/app
    command: npm run dev:backend
    networks:
      - hatch

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    # image: frontend:latest
    ports:
      - 5173:5173
    # volumes:
    #   - .:/app
    command: npm run dev:frontend
    networks:
      - hatch

networks:
  hatch:
    driver: bridge
