name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  Hatchify-Deploy-Postgres:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: deploy-postgres
        name: Deploy with postgres
        uses: bitovi/github-actions-deploy-docker-to-ec2@gha-testing
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
          aws_default_region: us-east-1

          # Provide a secret called `DOT_ENV` to append environment variables to the .env file
          # dot_env: ${{ secrets.DOT_ENV }}
          domain_name: bitovi-sandbox.com
          sub_domain: hatchify-grid-demo
          no_cert: true
          app_port: "5173,5174,3000,3001"
          lb_port: "5173,5174,3000,3001"
          lb_healthcheck: "HTTP:5173"

          ec2_volume_size: 20
          ec2_instance_type: t2.medium
          create_keypair_sm_entry: true

          docker_full_cleanup: true
          app_directory_cleanup: true 
          
          stack_destroy: true
          tf_state_bucket_destroy: true
          
